### ISSUE TITLE
[Feature Request] find circular dependencies of current file

### ISSUE THREAD

**Issue by tjx666** [olefjaerestad/vscode-circular-dependencies-finder#12]
In some very large project, the command `Find Circular Dependencies` will cause vscode window freeze. So, it would be useful to just find start current active textEditor

**Comment by olefjaerestad** [comment]
This would indeed be helpful! I don't have much time on my hands to get this done right now, but I will more than happily review a pull request. If not, I'll see if I can find time later (no promises though).

The freeze issue is also interesting. When does it freeze? After selecting `Find Circular Dependencies`, but before displaying the results?

**Comment by olefjaerestad** [comment]
A ['quickPick'](https://code.visualstudio.com/api/ux-guidelines/quick-picks) menu where you select 'in current file' or 'select file...' when running the 'Find Circular Dependencies' command has now been added. That should close this issue, and hopefully let you work around any freezes you experience due to many files in your projects.

The new quickpick is available in version 1.2.0 ([changelog](https://marketplace.visualstudio.com/items/olefjaerestad.vscode-circular-dependencies-finder/changelog)). Hope it works well for you. Thanks for the feedback!
